### ISSUE TITLE
Not detect linear-gradient syntax error

### ISSUE THREAD

**Issue by Yangfan2016** [cfjedimaster/vscode-csslint#8]
### error sample

```css
 .app-login {
    background-color:linear-gradient(180deg, #dbecff 20px 40px, rgba(219, 236, 255, 0) 50%);
}
```

### right samlpe
```css

 .app-login {
    background-color:linear-gradient(180deg, #dbecff 20px, rgba(219, 236, 255, 0) 50%);
}

```

### reason
![image](https://user-images.githubusercontent.com/17830872/59480677-2d6e0600-8e94-11e9-9238-a522166c5b47.png)
